- name: MySql configuration
  hosts: mysql
  become: yes
  tasks:
   - name: Install MySql Server
     ansible.builtin.package:
      name: mysql-server
      state: present
      enabled: yes
      start: yes